### ISSUE TITLE
chance twitter without the seed parameter always shows the same

### ISSUE THREAD

**Issue by openmedi** [chancejs/chance-cli#10]
OS: Os X 10.11.6

When using the cli with twitter without any seed parameter it ends up always showing the same handle. I assume that's a bug?

**Comment by benhurott** [comment]
Hi!

I open an pull request to fix it.
For now, you can install my fork until the mainteiner accepts it.

https://github.com/benhurott/chance-cli

**Comment by victorquinn** [comment]
Fixed by PR #9
